### ISSUE TITLE
Error: We couldn's open a connection with the Spam filter control pannel

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/zimbra-addon#9]
### Version information

Release 8.8.7_GA_1964.RHEL7_64_20180223145016 RHEL7_64 FOSS edition.
### Steps to replicate

 1. Client tries to install addon following the steps on the KB
2. Client gets the mentioned error

### Expected result
1. There should be no error

### Other notes

WHMCS: https://my.spamexperts.com/admin/supporttickets.php?action=view&id=213209
Client also attached the file he is uploading.

**Comment by claudiapetre** [comment]
The client tries to configure the addon using a domain user. Please, advise the client to use the admin who owns that domain.

**Comment by tonyandrewmeyer** [comment]
I assume that this is meant to be closed, since it has label:invalid.
